apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban-postgres
  template:
    metadata:
      labels:
        app: kanban-postgres
    spec:
      containers:
      - name: kanban-postgres
        image: "postgres:9.6-alpine"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: kanban
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kanban-postgres
spec:
  ports:
  - port: 5432
  selector:
    app: kanban-postgres
