name: kanban-app-deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        chmod 700 $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Set up Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy with Helm
      run: |
        helm dependency update ./kanban-board-microservices
        helm upgrade --install kanban-board-release ./kanban-board-microservices -f ./kanban-board-microservices/values.yaml --namespace kanban
